### ISSUE TITLE
Progress question

### ISSUE THREAD

**Issue by micooke** [sanpii/open-id107#1]
Hi, how is your progress? Have you managed to work out the pinout of the ribbon cable? There are 3 pins connected to gpio22-24 but i dont know what is sda, scl and what the third pin is for. For me it looks like [+4v][+3v3][?][?][?][GND][GND]. 

For reference: gpio4 and 7 are the two buttons, gpio6 is the vibrate. Im not sure what pin is used for measuring the battery voltage but i suspect it is gpio5

**Comment by sanpii** [comment]
> how is your progress?

I don’t work anymore on this project. I switched to a Mi band 1S that works fine with [gadgetbridge](https://gadgetbridge.org/).
